name: X-health-env
channels:
  - conda-forge
  - defaults
dependencies:
  - async-lru=2.0.4=pyhd8ed1ab_1
  - joblib=1.4.2=pyhd8ed1ab_1
  - jupyter=1.1.1=pyhd8ed1ab_1
  - jupyter-lsp=2.2.5=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_console=6.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - jupyter_events=0.11.0=pyhd8ed1ab_0
  - jupyter_server=2.15.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.3.4=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - jupyterlab_widgets=3.0.13=pyhd8ed1ab_1
  - matplotlib=3.9.4=py39hf3d152e_0
  - matplotlib-base=3.9.4=py39h16632d1_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - numpy=2.0.2=py39h9cb892a_1
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.2.3=py39h3b40f6f_2
  - python=3.9.21=h9c0c6dc_1_cpython
  - scikit-learn=1.5.0=py39h40c85ba_1
  - scipy=1.13.1=py39haf93ffa_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - xgboost=2.1.3=cpu_pyhc1a9e11_1
  - python=3.9
  - shap
  - pip 